name: Deploy Website to IPFS

on:
  push:
    branches:
      - main  # Runs the workflow on every push to the main branch

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install IPFS CLI
        run: |
          wget https://dist.ipfs.tech/kubo/v0.20.0/kubo_v0.20.0_linux-amd64.tar.gz
          tar -xvzf kubo_v0.20.0_linux-amd64.tar.gz
          cd kubo
          sudo install ipfs /usr/local/bin/ipfs

      - name: Initialize IPFS
        run: |
          ipfs init
          nohup ipfs daemon &  # Run IPFS in the background
          sleep 5  # Wait for IPFS to start

      - name: Upload Website to IPFS via HTTP API
        run: |
          RESPONSE=$(curl -s -F file=@index.html "http://127.0.0.1:5001/api/v0/add")
          CID=$(echo $RESPONSE | jq -r .Hash)
          echo "Website CID: $CID"
          echo "IPFS_CID=$CID" >> $GITHUB_ENV

      - name: Save IPFS CID as Artifact
        run: echo $IPFS_CID > ipfs_cid.txt

      - name: Upload CID Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IPFS_CID
          path: ipfs_cid.txt
