name: Deploy Website to IPFS

on:
  push:
    branches:
      - main  # Runs the workflow on every push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install IPFS CLI
        run: |
          wget https://dist.ipfs.tech/kubo/v0.20.0/kubo_v0.20.0_linux-amd64.tar.gz
          tar -xvzf kubo_v0.20.0_linux-amd64.tar.gz
          cd kubo
          sudo install ipfs /usr/local/bin/ipfs

      - name: Initialize IPFS
        run: |
          ipfs init
          nohup ipfs daemon &  # Run the IPFS daemon in the background

      - name: Upload Website to IPFS
        run: |
          CID=$(ipfs add -r --quieter . | tail -n1 | awk '{print $2}')
          echo "Website CID: $CID"
          echo "IPFS_CID=$CID" >> $GITHUB_ENV

      - name: Pin to Pinata
        env:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
        run: |
          curl -X POST "https://api.pinata.cloud/pinning/pinByHash" \
            -H "Content-Type: application/json" \
            -H "pinata_api_key: $PINATA_API_KEY" \
            -H "pinata_secret_api_key: $PINATA_SECRET_API_KEY" \
            --data "{ \"hashToPin\": \"$IPFS_CID\", \"pinataMetadata\": { \"name\": \"MyIPFSWebsite\" } }"
