name: Deploy Website to IPFS

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install IPFS on Windows
        run: |
          Invoke-WebRequest -Uri "https://dist.ipfs.tech/kubo/v0.22.0/kubo-windows-amd64.zip" -OutFile "ipfs.zip"
          Expand-Archive -Path "ipfs.zip" -DestinationPath "."
          cd kubo
          .\install.bat
          ipfs init

      - name: Start IPFS Daemon
        run: Start-Process -NoNewWindow -FilePath "ipfs.exe" -ArgumentList "daemon"

      - name: Add website files to IPFS
        run: |
          $CID = ipfs add -r -Q website
          echo "::debug::Website CID: $CID"
          echo "CID=$CID" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

